name: signal_router
description: A lightweight, signal-based routing library. Alpha version.
homepage: https://github.com/wildwind123/signal-router
repository: https://github.com/wildwind123/signal-router 
version: 1.0.0-alpha.1

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  alien_signals: ^1.0.3
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
